org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# AndroidX es obligatorio para proyectos modernos (en vez de las librerías de soporte antiguas)
android.useAndroidX=true
kotlin.code.style=official
# Evita que cada módulo "vea" los recursos R de otros módulos por accidente (buena práctica)
android.nonTransitiveRClass=true
